#!/bin/bash -x

# Creating main.tfvars
pushd ./rancher-ha

cat <<MAIN >> main-vars.tfvars
aws_access_key = "$AWS_ACCESS_KEY_ID"
aws_secret_key = "$AWS_SECRET_ACCESS_KEY"
aws_region = "$AWS_DEFAULT_REGION"
aws_env_name = "$AWS_ENV_NAME"
aws_s3_bucket = "$AWS_S3_BUCKET"
aws_vpc_id = "$AWS_VPC_ID"
aws_subnet_cidrs = "$AWS_SUBNET_CIDRS"
aws_subnet_ids = "$AWS_SUBNET_IDS"
MAIN


# Creating the AWS Bucket
set +e
aws s3 mb s3://${AWS_S3_BUCKET}
set -e
