#!/bin/bash

TIMEOUT=900
ELAPSED=0
FOUND=0

echo "Checking for https://${AWS_DOMAIN_NAME}"
while [ ${ELAPSED} -lt ${TIMEOUT} ]; do
  if curl -sfI --output /dev/null https://${AWS_DOMAIN_NAME}/v2-beta 2>&1; then
    FOUND=1
    break
  fi
  echo "."
  ELAPSED=$((ELAPSED + 10))
  sleep 10
done

if [ ${FOUND} -eq 1 ]; then
  echo "Rancher HA URL: https://${AWS_DOMAIN_NAME}"
else
  echo "Timeout Reached and setup is not ready...!!"
  exit 1
fi
